const {modifyWorker} = require("../notes/AST");

// https://webpack.js.org/concepts/loaders

module.exports = function (source) {
  const loaderContext = this;
  // loaderContext
  const {version,webpack} = loaderContext;
  // 对源代码 source 进行处理
  const modified = modifyWorker(source);

  const target = `
  /**
   * Loader API Version: ${version}
   * Is this in "webpack mode": ${webpack}
   */
  /**
   * Original Source From Loader
   */
   ${modified}`;

  // you can get resourcePath
  // loaderContext.resourcePath

  // you can get query
  // loaderContext.query

  // you can get options
  // loaderContext.options

  // cacheable
  this.cacheable(false);

  // emitFile
  this.emitFile('tmp/readme.md', 'generated by webpack loader', false);

  return target;
};
